import Providers from "@/components/Providers";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Navbar from "@/components/header/Navbar";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <Navbar /> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
